module.exports.ping = require("./ping")
module.exports.register = require("./register")
module.exports.help = require("./help")
module.exports.serverinfo = require("./serverinfo")
module.exports.corona = require("./corona")
module.exports.sat = require("./sat")
module.exports.say = require("./say")
module.exports.userinfo = require("./userinfo")
